### PR TITLE
fix MockSpan creation

### LINKED ISSUE #91: MockTracer passes Reference instead of MockSpanContext
## Background
I was investigating the usage of the OpenTracing API and found that the MockTracer is broken.

## Problem
This line:
https://github.com/opentracing/opentracing-php/blob/master/src/OpenTracing/Mock/MockTracer.php#L70
breaks due to the definition here:
https://github.com/opentracing/opentracing-php/blob/master/src/OpenTracing/Mock/MockSpanContext.php#L49
You are sending a Reference object but you are defining the function to only take MockSpanContext objects.

## Proposal
If you want the createAsChildOf to accept only MockSpanContexts, you will need to update the MockTracer to send $options->getReferences()[0]->getContext().
This update allows the MockTracer to not fail immediately.

## Questions to address
In what capacity do you want the MockTracer to work? 
In other words, should the MockTracer, and the Mock implementation in general, be considered the basis for a specific implementation of the OpenTracing API? 
Should the different objects interact explicitly as defined by the API? 
Or is the MockTracer just to show the minimum classes and functions that would be required for a tracing implementation and is not explicitly designed to work?
Should the Unit Tests catch this case?

### PR DESCRIPTION
**Pull request by cawolf**
### Short description of what this PR does:
- adds a test for `startSpan()` with references
- fixes the incompatibility mentioned in the issue
- increases the phpstan level (this would have caught the issue as well)

Closes #91

### CODE REVIEW

File: src/OpenTracing/Mock/MockTracer.php [hunk 1]
```diff
@@ -69,7 +70,11 @@ public function startSpan(string $operationName, $options = []): Span
         if (empty($options->getReferences())) {
             $spanContext = MockSpanContext::createAsRoot();
         } else {
-            $spanContext = MockSpanContext::createAsChildOf($options->getReferences()[0]);
+            $referenceContext = $options->getReferences()[0]->getContext();
+            if (!$referenceContext instanceof MockSpanContext) {
```
Comment (jcchavezs) [inline src/OpenTracing/Mock/MockTracer.php]: I am always afraid of doing `if (!$something instanceof ...)` I usually do `if (!($something instanceof ...))`. Would you add a failing test case for this?

Comment (cawolf) [reply src/OpenTracing/Mock/MockTracer.php]: Is there a reason for your fear? [The official PHP documentation](https://www.php.net/manual/en/language.operators.precedence.php) is very clear about operator precedence. :) 

But sure, I will add a test case for the exception branch.

Comment (jcchavezs) [reply src/OpenTracing/Mock/MockTracer.php]: interesting I did not know about it, I guess my fear was because the dynamic typing.

**Comment by jcchavezs** [comment]
Thanks a lot @cawolf
